[project]
name = "goserialize"
author = "Polshkrev"
description = "A simple golang serialization library."

[project.version]
minor = 7

[license]
type = "MIT"
path = "LICENSE"

[urls]
repository = "github.com/Polshkrev/goserialize"

[paths]
readme = "README.md"